### PR TITLE
Fix wrongly refactored title in the readme

### PR DESCRIPTION
**Pull request by MiniDigger**
was introduced in #13

### CODE REVIEW

**Comment by SamB440** [comment]
lol

**Comment by yannicklamprecht** [comment]
https://github.com/Chazmondo/AdvancementAPI/blob/master/src/main/java/io/chazza/advancementapi/AdvancementAPI.java#L248

**Comment by MiniDigger** [comment]
Somebody needs to up their review process, lol

**Comment by JarvisCraft** [comment]
Great

**Comment by Ry-DS** [comment]
When I used intellij to move the class to a package, it replaced all mentions of the class to src.class 😛. Should have fix all the rest as well

**Comment by Skill** [comment]
Is it possible to get someone in charge of this? Being honest I have 0 clue with Github and would rather allow a "Contributor" to manage this, does Github allow it?

**Comment by Chazmondo** [comment]
Kind of tempted to revert lots of this, it's gone so complex and confusing for people >.<

**Comment by Ry-DS** [comment]
You can add someone as a person with push access. Then they can edit the pull request/review aswell as you. But they can also push to master. Maybe there is a setting for a reviewer?

**Comment by yannicklamprecht** [comment]
I’ll recommend not pushing to master by default. Each feature one branch during development. Then on merge delete branch.

**Comment by Ry-DS** [comment]
I was just mentioning the reviewer would have to have access to it.

**Pull request merged**
